/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DrawIndexImport } from './routes/draw.index'
import { Route as DrawIdImport } from './routes/draw.$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DrawIndexRoute = DrawIndexImport.update({
  id: '/draw/',
  path: '/draw/',
  getParentRoute: () => rootRoute,
} as any)

const DrawIdRoute = DrawIdImport.update({
  id: '/draw/$id',
  path: '/draw/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/draw/$id': {
      id: '/draw/$id'
      path: '/draw/$id'
      fullPath: '/draw/$id'
      preLoaderRoute: typeof DrawIdImport
      parentRoute: typeof rootRoute
    }
    '/draw/': {
      id: '/draw/'
      path: '/draw'
      fullPath: '/draw'
      preLoaderRoute: typeof DrawIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/draw/$id': typeof DrawIdRoute
  '/draw': typeof DrawIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/draw/$id': typeof DrawIdRoute
  '/draw': typeof DrawIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/draw/$id': typeof DrawIdRoute
  '/draw/': typeof DrawIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/draw/$id' | '/draw'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/draw/$id' | '/draw'
  id: '__root__' | '/' | '/draw/$id' | '/draw/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrawIdRoute: typeof DrawIdRoute
  DrawIndexRoute: typeof DrawIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrawIdRoute: DrawIdRoute,
  DrawIndexRoute: DrawIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/draw/$id",
        "/draw/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/draw/$id": {
      "filePath": "draw.$id.tsx"
    },
    "/draw/": {
      "filePath": "draw.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
